apiVersion: v1
kind: Service
metadata:
  name: main-srv
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/part-of: kube-system
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000